services:
  postgres:
    image: postgres:16
    container_name: lakehouse-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: lakehouse-minio
    env_file:
      - .env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  trino:
    image: trinodb/trino:latest
    container_name: lakehouse-trino
    ports:
      - "8080:8080"
    volumes:
      - ./docker/trino/etc:/etc/trino
    depends_on:
      - minio
      - postgres

volumes:
  postgres_data:
  minio_data: